 spring:
    application:
      name: api
    datasource:
      url: jdbc:postgresql://localhost:5432/api
      username: api
      password: api
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      open-in-view: false
